services:
  db:
    image: mysql:8.3
    container_name: databae
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - ${DATABASE_PORT}:3306
    volumes:
      - db_data:/var/lib/mysql
    networks:
      main:
        aliases:
          - db

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: ${DB_USERNAME}
      PMA_PASSWORD: ${DB_PASSWORD}
      PMA_ARBITRARY: 0
      UPLOAD_LIMIT: 1G
    ports:
      - ${PHPMYADMIN_PORT}:80
    depends_on:
      - db
    networks:
      main:
        aliases:
          - phpmyadmin

  nginx:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DOMAIN: _
        PROXY_PORT: 5000
    ports:
      - "${APP_PORT}:5000"
    environment:
      VIRTUAL_HOST: ${DOMAIN}
      VIRTUAL_PORT: 5000
    volumes:
      - ./.env:/var/www/html/backend/.env
    depends_on:
      - db
    networks:
      main:
        aliases:
          - nginx
  # app:
  #   build:
  #     context: .
  #     dockerfile: DockerBun
  #     args:
  #       NUXT_PUBLIC_API_URL: ${NUXT_PUBLIC_API_URL}
  #   ports:
  #     - "3000"
  #   volumes:
  #     - ./.env:/app/.env
  #   networks:
  #     main:
  #       aliases:
  #         - app
  #   depends_on:
  #     - nginx

  # supervisor:
  #   build:
  #     context: .
  #     dockerfile: DockerSupervisor
  #   volumes:
  #     - ./.env:/var/www/html/backend/.env
  #   networks:
  #     main:
  #       aliases:
  #         - supervisor
  #   depends_on:
  #       - db
  #       - nginx

volumes:
  db_data:

networks:
  main:
